DROP TABLE SCIENCE CASCADE;
DROP TABLE ISSUE CASCADE;
DROP TABLE GROUP_INFO CASCADE;
DROP TABLE PERSON CASCADE;
DROP TABLE DEBATE CASCADE;
DROP TABLE GROUP_PERSON CASCADE;


CREATE TABLE SCIENCE(
	ID SERIAL PRIMARY KEY,
	NAME varchar(255),
	TYPE varchar(255));

CREATE TABLE ISSUE(
	ID SERIAL PRIMARY KEY,
	NAME varchar(16383),
	STATUS boolean);

CREATE TABLE GROUP_INFO(
	ID SERIAL PRIMARY KEY,
	STATUS boolean,
	ISSUE_ID integer REFERENCES ISSUE);

CREATE TABLE PERSON(
	ID SERIAL PRIMARY KEY,
	NAME varchar(255),
	SURNAME varchar(255));

CREATE TABLE DEBATE(
	ID SERIAL PRIMARY KEY,
	SCIENCE_ID integer REFERENCES SCIENCE,
	POSITIVE_GROUP_ID integer REFERENCES GROUP_INFO,
	NEGATIVE_GROUP_ID integer REFERENCES GROUP_INFO,
	ISSUE_ID integer REFERENCES ISSUE);


CREATE TABLE GROUP_PERSON(
	ID SERIAL PRIMARY KEY,
	PERSON_ID integer REFERENCES PERSON,
	GROUP_ID integer REFERENCES GROUP_INFO);


INSERT INTO SCIENCE VALUES(DEFAULT, 'физика', 'атомная');
INSERT INTO SCIENCE VALUES(DEFAULT, 'биология', 'генетика');
INSERT INTO SCIENCE VALUES(DEFAULT, 'информатика', 'web');

INSERT INTO ISSUE VALUES(DEFAULT, 'бабах или не бабах?', true);
INSERT INTO ISSUE VALUES(DEFAULT, 'может ли родить мужчина?', false);
INSERT INTO ISSUE VALUES(DEFAULT, 'все ли мы будем перекладывать jsonы?', null);

INSERT INTO GROUP_INFO VALUES(DEFAULT, true, 1);
INSERT INTO GROUP_INFO VALUES(DEFAULT, false, 1);
INSERT INTO GROUP_INFO VALUES(DEFAULT, true, 2);
INSERT INTO GROUP_INFO VALUES(DEFAULT, false, 2);
INSERT INTO GROUP_INFO VALUES(DEFAULT, true, 3);
INSERT INTO GROUP_INFO VALUES(DEFAULT, false, 3);

INSERT INTO PERSON VALUES(DEFAULT, 'Иван', 'Лопатин');
INSERT INTO PERSON VALUES(DEFAULT, 'Данил', 'Путинцев');
INSERT INTO PERSON VALUES(DEFAULT, 'Милана', 'Александрова');
INSERT INTO PERSON VALUES(DEFAULT, 'Дмитрий', 'Карпов');
INSERT INTO PERSON VALUES(DEFAULT, 'Алексей', 'Пастор');
INSERT INTO PERSON VALUES(DEFAULT, 'Екатерина', 'Трифанова');
INSERT INTO PERSON VALUES(DEFAULT, 'Артем', 'Назин');
INSERT INTO PERSON VALUES(DEFAULT, 'Мария', 'Брель');
INSERT INTO PERSON VALUES(DEFAULT, 'Игорь', 'Булинин');
INSERT INTO PERSON VALUES(DEFAULT, 'Пикачу', 'Письмак');
INSERT INTO PERSON VALUES(DEFAULT, 'ПСЖ', 'Балакшин');
INSERT INTO PERSON VALUES(DEFAULT, 'Покемон', 'Клименков');

INSERT INTO DEBATE VALUES(DEFAULT, 1, 1, 2, 1);
INSERT INTO DEBATE VALUES(DEFAULT, 2, 3, 4, 2);
INSERT INTO DEBATE VALUES(DEFAULT, 3, 5, 6, 3);

INSERT INTO GROUP_PERSON VALUES(DEFAULT, 1, 1);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 1, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 2, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 2, 6);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 2, 1);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 3, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 3, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 3, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 4, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 4, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 4, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 5, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 5, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 5, 6);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 6, 1);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 6, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 7, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 8, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 8, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 9, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 10, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 11, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 12, 3);
