DROP TABLE SCIENCE CASCADE;
DROP TABLE ISSUE CASCADE;
DROP TABLE GROUP_INFO CASCADE;
DROP TABLE PERSON CASCADE;
DROP TABLE DEBATE CASCADE;
DROP TABLE TYPE_INFO CASCADE;
DROP TABLE GROUP_PERSON CASCADE;
DROP TYPE group_enum CASCADE;
DROP TYPE issue_enum CASCADE;
DROP TYPE type_enum CASCADE;

CREATE TYPE group_enum AS ENUM('Positive', 'Negative', 'NULL');
CREATE TYPE issue_enum AS ENUM('Resolved', 'Relevant', 'Not resolved', 'NULL');
CREATE TYPE type_enum AS ENUM('Resolved', 'Relevant', 'Not resolved', 'NULL');

CREATE TABLE TYPE_INFO(
	ID SERIAL PRIMARY KEY,
	NAME varchar(255) NOT NULL,
	STATUS type_enum NOT NULL);

CREATE TABLE ISSUE(
	ID SERIAL PRIMARY KEY,
	NAME varchar(16383) UNIQUE,
	STATUS issue_enum);

CREATE TABLE SCIENCE(
	ID SERIAL PRIMARY KEY,
	NAME varchar(255) UNIQUE NOT NULL,
	TYPE_ID integer REFERENCES TYPE_INFO NOT NULL);

CREATE TABLE GROUP_INFO(
	ID SERIAL PRIMARY KEY,
	STATUS group_enum,
	ISSUE_ID integer REFERENCES ISSUE);

CREATE TABLE PERSON(
	ID SERIAL PRIMARY KEY,
	NAME varchar(255) NOT NULL,
	SURNAME varchar(255) NOT NULL);

CREATE TABLE DEBATE(
	ID SERIAL PRIMARY KEY,
	SCIENCE_ID integer REFERENCES SCIENCE NOT NULL,
	POSITIVE_GROUP_ID integer REFERENCES GROUP_INFO NOT NULL,
	NEGATIVE_GROUP_ID integer REFERENCES GROUP_INFO NOT NULL,
	ISSUE_ID integer REFERENCES ISSUE NOT NULL,
	CHECK(POSITIVE_GROUP_ID != NEGATIVE_GROUP_ID));


CREATE TABLE GROUP_PERSON(
	ID SERIAL PRIMARY KEY,
	PERSON_ID integer REFERENCES PERSON NOT NULL,
	GROUP_ID integer REFERENCES GROUP_INFO NOT NULL);

INSERT INTO TYPE_INFO VALUES(DEFAULT, 'атомная', 'Resolved');
INSERT INTO TYPE_INFO VALUES(DEFAULT, 'генетика', 'Not resolved');
INSERT INTO TYPE_INFO VALUES(DEFAULT, 'веб', 'Relevant');


INSERT INTO SCIENCE VALUES(DEFAULT, 'физика', 1);
INSERT INTO SCIENCE VALUES(DEFAULT, 'биология', 2);
INSERT INTO SCIENCE VALUES(DEFAULT, 'информатика', 3);

INSERT INTO ISSUE VALUES(DEFAULT, 'бабах или не бабах?', 'Resolved');
INSERT INTO ISSUE VALUES(DEFAULT, 'может ли родить мужчина?', 'Relevant');
INSERT INTO ISSUE VALUES(DEFAULT, 'все ли мы будем перекладывать jsonы?', 'Relevant');

INSERT INTO GROUP_INFO VALUES(DEFAULT, 'Positive', 1);
INSERT INTO GROUP_INFO VALUES(DEFAULT, 'Negative', 1);
INSERT INTO GROUP_INFO VALUES(DEFAULT, 'Positive', 2);
INSERT INTO GROUP_INFO VALUES(DEFAULT, 'Negative', 2);
INSERT INTO GROUP_INFO VALUES(DEFAULT, 'Positive', 3);
INSERT INTO GROUP_INFO VALUES(DEFAULT, 'Negative', 3);

INSERT INTO PERSON VALUES(DEFAULT, 'Иван', 'Лопатин');
INSERT INTO PERSON VALUES(DEFAULT, 'Данил', 'Путинцев');
INSERT INTO PERSON VALUES(DEFAULT, 'Милана', 'Александрова');
INSERT INTO PERSON VALUES(DEFAULT, 'Дмитрий', 'Карпов');
INSERT INTO PERSON VALUES(DEFAULT, 'Алексей', 'Пастор');
INSERT INTO PERSON VALUES(DEFAULT, 'Екатерина', 'Трифанова');
INSERT INTO PERSON VALUES(DEFAULT, 'Артем', 'Назин');
INSERT INTO PERSON VALUES(DEFAULT, 'Мария', 'Брель');
INSERT INTO PERSON VALUES(DEFAULT, 'Игорь', 'Булинин');
INSERT INTO PERSON VALUES(DEFAULT, 'Пикачу', 'Письмак');
INSERT INTO PERSON VALUES(DEFAULT, 'ПСЖ', 'Балакшин');
INSERT INTO PERSON VALUES(DEFAULT, 'Покемон', 'Клименков');

INSERT INTO GROUP_PERSON VALUES(DEFAULT, 1, 1);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 1, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 2, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 2, 6);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 2, 1);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 3, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 3, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 3, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 4, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 4, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 4, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 5, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 5, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 5, 6);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 6, 1);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 6, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 7, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 8, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 8, 5);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 9, 2);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 10, 4);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 11, 3);
INSERT INTO GROUP_PERSON VALUES(DEFAULT, 12, 3);


INSERT INTO DEBATE VALUES(DEFAULT, 1, 1, 2, 1);
INSERT INTO DEBATE VALUES(DEFAULT, 2, 3, 4, 2);
INSERT INTO DEBATE VALUES(DEFAULT, 3, 5, 6, 3);



