name: capital_case_cstr
limit: 1000
memory_size: 0x1000
input_streams:
  0x80: [72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68, 33, 10]
  0x84: []
reports:
  - name: Step-by-step
    slice: all
    view: |
      {pc}: {instruction} {pc:label}
  - name: Result
    slice: last
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
      numio[0x80]: {io:0x80:sym}
      numio[0x84]: {io:0x84:sym}