DROP TABLE IF EXISTS "OrderProduct" CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS "ProductInfo" CASCADE;
DROP TABLE IF EXISTS "Product" CASCADE;
DROP TABLE IF EXISTS "OrderStatus" CASCADE;

DROP TABLE IF EXISTS "AccountRole" CASCADE;
DROP TABLE IF EXISTS "Role" CASCADE;

DROP TABLE IF EXISTS "Tournament" CASCADE;
DROP TABLE IF EXISTS "Rang" CASCADE;

DROP TABLE IF EXISTS "Attachment" CASCADE;
DROP TABLE IF EXISTS "TypeAttachment" CASCADE;

DROP TABLE IF EXISTS "TagPost" CASCADE;
DROP TABLE IF EXISTS "Tag" CASCADE;

DROP TABLE IF EXISTS "Comment" CASCADE;
DROP TABLE IF EXISTS "Post" CASCADE;

DROP TABLE IF EXISTS "Account" CASCADE;

DROP SEQUENCE IF EXISTS account_account_id_seq CASCADE;
DROP SEQUENCE IF EXISTS post_post_id_seq CASCADE;
DROP SEQUENCE IF EXISTS comment_comment_id_seq CASCADE;
DROP SEQUENCE IF EXISTS typeattachment_type_id_seq CASCADE;
DROP SEQUENCE IF EXISTS attachment_attachment_id_seq CASCADE;
DROP SEQUENCE IF EXISTS tag_tag_id_seq CASCADE;
DROP SEQUENCE IF EXISTS tagpost_tag_post_id_seq CASCADE;
DROP SEQUENCE IF EXISTS rang_rang_id_seq CASCADE;
DROP SEQUENCE IF EXISTS tournament_tournament_id_seq CASCADE;
DROP SEQUENCE IF EXISTS role_role_id_seq CASCADE;
DROP SEQUENCE IF EXISTS accountrole_account_role_id_seq CASCADE;
DROP SEQUENCE IF EXISTS orderstatus_status_id_seq CASCADE;
DROP SEQUENCE IF EXISTS order_order_id_seq CASCADE;
DROP SEQUENCE IF EXISTS product_product_id_seq CASCADE;
DROP SEQUENCE IF EXISTS productinfo_product_info_id_seq CASCADE;
DROP SEQUENCE IF EXISTS orderproduct_order_product_id_seq CASCADE;
